sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t junseok0216/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true junseok0216/docker-react-app

after_success:
  - echo "Test Success"